### ISSUE TITLE
Add to the readme: how to change the delimiter

### ISSUE THREAD

**Issue by liavassif** [wavexx/python-x.el#12]
I would guess one of the first thing people would like to know is how to set the section delimiter. Many IDEs use "# %%". While everything is documented very well, a comment in the readme would be helpful:
    (setq python-section-delimiter "# %%")

**Comment by wavexx** [comment]
On Mon, May 15 2017, liavassif wrote:
> I would guess one of the first thing people would like to know is how
> to set the section delimiter. Many IDEs use "# %%". While everything
> is documented very well, a comment in the readme would be helpful:
>
>     (setq python-section-delimiter "# %%")

Sure, makes sense. Can I ask which editor uses "# %%" by default?

**Comment by liavassif** [comment]
Spyder and Pyzo support it. I think the default in Pyzo is "##" though

**Comment by liavassif** [comment]
Thanks

**Comment by wavexx** [comment]
Took longer than expected ;)
